---
title: "Assignment_01"
author: "Fatima Arshad"
date: "1/23/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

# Import libraries
library(tidyverse)
library(fixest)
library(caret)
library(modelsummary)
library(grid)
library(ggplot2)
library(gridExtra)
library(kableExtra)
```

## R Markdown

```{r include=FALSE}
df <- read_csv("https://osf.io/4ay9x/download")

# Choosing variables of interest
df <- df %>% select(occ2012, earnwke, uhours, grade92, age, sex, ownchild, marital)

#Filter data for computer and mathematical occupations
df <- df %>% filter(occ2012 == 1005 | occ2012 == 1006 | occ2012 == 1007 |  
                 occ2012 == 1010 | occ2012 == 1020 | occ2012 == 1030 | 
                 occ2012 == 1050 | occ2012 == 1060 |occ2012 == 1105 | 
                 occ2012 == 1106 | occ2012 == 1107)

```



```{r}
##### Introduction:
This report uses the **Accountants and auditors** occupation groupfrom the [cps-earnings dataset](https://osf.io/g8p9j/) to build four predictive models using linear regression for earnings per hour. The BIC, RMSE, and five-fold cross-validation for cross-validated RMSE is calculated to discuss the relationship between model complexity and performance.

##### Data Cleaning, Exploration, and Factoring:
Age is modeled as its squared non-linearity for a regression with log hourly wage as the dependent variable. The following subset of predictor variables are considered for the purpose of this analysis: education level (Bachelor degree as base), age (squared), sex (male as base), number of children (squared and cubic), and marital status (not married as base). *Refer to Appendix for further details.* 
```


```{r}
#Checking for missing values
df <- na.omit(df)
sum(is.na(df))

# Define variables

# Adding hourly wages
df$w <- df$earnwke/df$uhours

# Explore predictor variables
v1 <- ggplot( data = df, aes( x = as.factor(sex)) )  +
  geom_bar(aes(y = (..count..)/sum(..count..)), color='dodgerblue4',fill='dodgerblue3', alpha=0.5) +
  theme_bw() +
  labs( x = NULL, y = NULL, title = 'Distribution of Sex') +
  theme( plot.title = element_text(hjust = 0.5 ) )

v2 <- ggplot( data = df, aes( x = age) )  +
  geom_bar(aes(y = (..count..)/sum(..count..)), color='dodgerblue4',fill='dodgerblue3', alpha=0.5) +
  theme_bw() +
  labs( x = NULL, y = NULL, title = 'Distribution of Age') +
  theme( plot.title = element_text(hjust = 0.5 ) )

v3 <- ggplot( data = df, aes( x = grade92) )  +
  geom_bar(aes(y = (..count..)/sum(..count..)), color='dodgerblue4',fill='dodgerblue3', alpha=0.5) +
  theme_bw() +
  labs( x = NULL, y = NULL, title = 'Distribution of \n Education Level') +
  theme( plot.title = element_text(hjust = 0.5 ) )

v4 <- ggplot( data = df, aes( x = ownchild) )  +
  geom_bar(aes(y = (..count..)/sum(..count..)), color='dodgerblue4',fill='dodgerblue3', alpha=0.5) +
  theme_bw() +
  labs( x = NULL, y = NULL, title = 'Distribution of \n Having Children') +
  theme( plot.title = element_text(hjust = 0.5 ) )

v5 <- ggplot( data = df, aes( x = marital) )  +
  geom_bar(aes(y = (..count..)/sum(..count..)), color='dodgerblue4',fill='dodgerblue3', alpha=0.5) +
  theme_bw() +
  labs( x = NULL, y = NULL, title = 'Distribution of \n Marital Status') +
  theme( plot.title = element_text(hjust = 0.5 ) )

################################################

#Filter marital: 2, 3, 4, 6
df <- filter( df, !marital %in%  c(2, 3, 4, 6))

#Filter grade92: 32, 33, 34, 35, 36, 37, 38
df <- filter( df, !grade92 %in%  c(32, 33, 34, 35, 36, 37, 38))

#Changing for degree with Bachelor Degree as base
df <- df %>% mutate("Bachelor_Associate_Degree"=as.numeric(grade92==43 | grade92==41 | grade92==42),
                      "Higher_Than_Bachelor" = as.numeric(grade92==44 | grade92==45 | grade92==46),
                      "College" = as.numeric(grade92==40),
                      "High_School" = as.numeric(grade92==39))

# Change sex: Male is 0 and Female is 1
df$sex <- ifelse(df$sex == 1, 0, 1)
df$female <- df$sex

# Change marriage with Not Married as base
df <- df %>% mutate("Not Married"=as.numeric(marital==0),
                                    "Married" = as.numeric(marital==7),
                                    "Divorced" = as.numeric(marital==5))

# Add quadratic age
df <- df %>% mutate(agesq = age^2)

#Add square of ownchild
df <- df %>% mutate(ownchildsq = ownchild^2)

# Exploring distribution for log wages
log1 <- ggplot(data=df, aes(x=w)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 10, boundary=0,
                 fill = 'dodgerblue3', color = 'white', size = 0.25, alpha = 0.8,  show.legend=F, na.rm=TRUE) +
  coord_cartesian(xlim = c(0, 1000)) +
  labs(x = "Hourly Wages", y = NULL)+
  theme_bw() 

# Add log hourly wage
df$lnw <- log(df$w)

# Visualize distribution for log hourly wage
log2 <- ggplot(data=df, aes(x=lnw)) +
  geom_histogram(aes(y = (..count..)/sum(..count..)), binwidth = 0.2, boundary=0,
                 fill = 'dodgerblue3', color = 'white', size = 0.25, alpha = 0.8,  show.legend=F, na.rm=TRUE) +
  coord_cartesian(xlim = c(-2, 7)) +
  labs(x = "ln(Hourly Wages)", y = NULL)
  theme_bw() 

##############################################

# Lowess with observations log earnings per Hour and Age
lowess1 <- ggplot(data = df, aes(x=age, y=lnw)) +
  geom_point( color = 'deepskyblue3', size = 0.7,  shape = 16, alpha = 0.8, show.legend=F, na.rm = TRUE) + 
  geom_smooth(method="loess", se=F, colour='darkblue', size=1, span=0.9) +
  theme_bw() +
  expand_limits(x = 0.01, y = 0.01) +
  scale_x_continuous(expand = c(0.01,0.01),limits = c(16,64), breaks = seq(0,64, 10)) +
  scale_y_continuous(expand = c(0.01,0.01),limits = c(-4,7), breaks = seq(-4,7, 1)) +
  labs( x = "Age", y = "Log Earnings per Hour", title = 'Lowess with Observations for earnings per hour and age') +
  theme( plot.title = element_text(hjust = 0.5 ) )

# Lowess vs. quadratic Age
lowess2 <- ggplot(data = df, aes(x=age,y=lnw)) +
  geom_point( aes( y = lnw ) , color = 'deepskyblue3', size = 0.7,  shape = 16, alpha = 0.8, show.legend=F, na.rm = TRUE) + 
  geom_smooth( aes(colour='darkblue'), method="lm", formula = y ~ poly(x,2) , se=F, size=1) +
  geom_smooth( aes(colour='brown'), method="loess", formula = y ~ x,se=F, size=1) +
  labs(x = "Age",y = "Log Earnings per Hour", title = 'Lowess with Observations for quadratic age') +
  scale_color_manual(name="", values=c('brown','darkblue'),labels=c("Lowess in Earnings","Quadratic in Earnings")) +
  theme_bw() +
  scale_x_continuous(limits = c(16,64), breaks = seq(16,64, 10)) +
  scale_y_continuous(limits = c(-4,7), breaks = seq(-4,7, 1)) +
  theme(legend.position = c(0.5,0.3),
        legend.direction = "horizontal",
        legend.background = element_blank(),
        legend.box.background = element_rect(color = "white"),
        plot.title = element_text(hjust = 0.5))

# Lowess with observations for Earnings per Hour and Number of Children
lowess4 <- ggplot(data = df, aes(x=ownchild, y=lnw)) +
  geom_point( color = 'deepskyblue3', size = 1,  shape = 16, alpha = 0.8, show.legend=F, na.rm = TRUE) + 
  geom_smooth(method="loess", se=F, colour='darkblue', size=1, span=0.9) +
  theme_bw() +
  expand_limits(x = 0.01, y = 0.01) +
  scale_x_continuous(expand = c(0.01,0.01),limits = c(0,6), breaks = seq(0,6, 1)) +
  scale_y_continuous(expand = c(0.01,0.01),limits = c(-4,7), breaks = seq(-4,7, 1)) +
  labs( x = "Number of Children", y = "Log Earnings per Hour", title = 'Lowess with Observations for Earnings per Hour and Number of Children') +
  theme( plot.title = element_text(hjust = 0.5 ) )

# Lowess vs. quadratic number of children
lowess5 <- ggplot(data = df, aes(x=ownchild,y=lnw)) +
  geom_point( aes( y = lnw ) , color = 'deepskyblue3', size = 1,  shape = 16, alpha = 0.8, show.legend=F, na.rm = TRUE) + 
  geom_smooth( aes(colour='darkblue'), method="lm", formula = y ~ poly(x,2) , se=F, size=1) +
  geom_smooth( aes(colour='brown'), method="loess", formula = y ~ x,se=F, size=1) +
  labs(x = "Number of Children",y = "Log Earnings per Hour", title = 'Lowess with Observations') +
  scale_color_manual(name="", values=c('brown','darkblue'),labels=c("Lowess in Earnings","Quadratic in Earnings")) +
  theme_bw() +
  scale_x_continuous(limits = c(0,6), breaks = seq(0,6, 1)) +
  scale_y_continuous(limits = c(-4,7), breaks = seq(-4,7, 1)) +
  theme(legend.position = c(0.5,0.3),
        legend.direction = "horizontal",
        legend.background = element_blank(),
        legend.box.background = element_rect(color = "white"),
        plot.title = element_text(hjust = 0.5))

################################################################################

# Define linear regression models
model1 <- as.formula(lnw ~ age + agesq)
model2 <- as.formula(lnw ~ age + agesq + female)
model3 <- as.formula(lnw ~ age + agesq + female + 
                       Higher_Than_Bachelor + College + High_School + 
                       ownchild + ownchildsq)
model4 <- as.formula(lnw ~ age + agesq + female +
                       Higher_Than_Bachelor + College + High_School +
                       ownchild + ownchildsq + Married + 
                       Divorced + Married*age + 
                       Married*Higher_Than_Bachelor + Married*female )

#Running OLS regressions with models
reg1 <- feols(model1, data=df, vcov = 'hetero')
reg2 <- feols(model2, data=df, vcov = 'hetero')
reg3 <- feols(model3, data=df, vcov = 'hetero')
reg4 <- feols(model4, data=df, vcov = 'hetero')


#################################################################################

```

```{r}

```

```{r}


```


